name: Publish RubyGem

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - uses: rubygems/configure-rubygems-credentials@v1
      - run: gem build bee-holy-scripture.gemspec
      - run: gem push bee-holy-scripture-*.gem
